<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>localhost</title>
</head>
<body>
  <h1>PHP Data Objects (PDO)</h1>
  <h2>Tasks:</h2>
  <ul>
    <?php foreach ($tasks as $task) : ?>
      <li>
        <?php if ($task->completed) : ?>
          <strike><?= $task->description; ?></strike>
        <?php else : ?>
          <?= $task->description; ?>
        <?php endif; ?>
      </li>
    <?php endforeach; ?>
  </ul>

  <h2>Range Gen:</h2>
    <?php generateRange(5, 55); ?>
</body>
</html>