<?php require('partials/header.php'); ?>
  
  
  <h1>Index View Page</h1>
  

  <h2>Tasks:</h2>
  <ul>
    <?php foreach ($tasks as $task) : ?>
      <li>
        <?php if ($task->completed) : ?>
          <strike><?= $task->description; ?></strike>
        <?php else : ?>
          <?= $task->description; ?>
        <?php endif; ?>
      </li>
    <?php endforeach; ?>
  </ul>

  <h2>Range Gen:</h2>
    <?php generateRange(5, 15); ?>


<?php require('partials/footer.php') ?>