version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'php-sandbox-webserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-../}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mysql:
    build: ./bin/mysql
    container_name: 'php-sandbox--mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: phpsandbox
      MYSQL_DATABASE: phpsandbox
      MYSQL_USER: phpsandbox
      MYSQL_PASSWORD: phpsandbox
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'php-sandbox-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes: 
      - /sessions
  redis:
    container_name: 'php-sandbox-redis'
    image: redis:latest
    ports:
      - "6379:6379"
