<?php require('partials/header.php'); ?>
  
  
  <h1>Homepage</h1>
  


  <!-- <h2>Tasks:</h2>
  <ul>
    <?php foreach ($tasks as $task) : ?>
      <li>
        <?php if ($task->completed) : ?>
          <strike><?= $task->description; ?></strike>
        <?php else : ?>
          <?= $task->description; ?>
        <?php endif; ?>
      </li>
    <?php endforeach; ?>
  </ul>




  <h2>Range Gen:</h2>
    <?php generateRange(5, 10); ?>



  <h2>Enter your Name:</h2>
  <form method="POST" action="/names">
    <input name="name">
    <button type="submit">Submit</button>
  </form>


  <h2>Names:</h2>
  <ul>
    <?php foreach ($users as $user) : ?>
      <li>
        <?= $user->name; ?>
      </li>
    <?php endforeach; ?>
  </ul> -->

<?php require('partials/footer.php') ?>